version: '3'
services:
  desktop:
    image: elestio/ubuntu-desktop:${SOFTWARE_VERSION_TAG}
    restart: always
    dns:
      - 8.8.8.8
    ports:
      - "172.17.0.1:6901:6901"
      - "172.17.0.1:4901:4901"
    volumes:
      - ./data:/home/kasm-user
      - ./scripts/vnc_startup.sh:/dockerstartup/vnc_startup.sh
      - ./data-src/jsmpeg:/dockerstartup/jsmpeg
      - ./data-src/jsmpeg/injectaudio.js:/usr/share/kasmvnc/www/dist/style.bundle.js
      - ./data-src/jsmpeg/jsmpeg.min.js:/usr/share/kasmvnc/www/dist/jsmpeg.min.js
      - ./data-src/jsmpeg/audio.html:/usr/share/kasmvnc/www/dist/audio.html
    shm_size: '512m'
    environment:
      VNC_USER: ${ADMIN_LOGIN}
      VNC_PW: ${ADMIN_PASSWORD}
